### ISSUE TITLE
incorrect file during setup 

### ISSUE THREAD

**Issue by trancen** [captain-coredump/weatherflow-udp#1]
install.py file is looking for the "bin/user/weatherflowudp.py" file but in the git the file found in "bin/user/" is udpbroadcast.py

**Comment by captain-coredump** [comment]
Oops!  I changed the name to weatherflowudp.py right before I did the initial post, and did not rename the file.  I'll fix it when I upload the latest version this weekend, which includes decoding for additional packet types.

FWIW, this code may not be pretty, but it has been 100% stable for the few months that I've been running it in a test weewx instance.....

**Comment by trancen** [comment]
Not a problem  figured out the problem and renamed it. I setup weewx on my
VPS which is outside of my home network. I have to see if I can get it to
work. Is there any additional settings you make in the weewx configuration
file? This is the first time I have used weewx

**Comment by captain-coredump** [comment]
I hate to be the bearer of bad news, but the UDP broadcast packets are only visible on the local subnet where the WeatherFlow Bridge resides.  As written, the code will not work from a VPS host.

If you really want to run weewx from a VPS host, you will need to look at implementing either of the available web-based API calls (REST or WebSocket):

[https://weatherflow.github.io/SmartWeather/api/](url)

I'm running weewx on a Raspberry Pi 3, and have it (on my production weather station) pushing the data up to MeteoTemplate on a VPS server.  There is a MeteoTemplate uploader in mwall's GitHub repository, and it will send realtime data from the local Pi's weewx implementation to MeteoTemplate as the packets arrive.

If you have never looked at MeteoTemplate, it is a gazillion times better as a web presentation layer than weewx's simplistic web pages.  Jachym has done an awesome job with this free template, and has a demo site on meteotemplate.com.  If you want to check out my installation (running on a Pi 3 and getting data from my Acu-Rite station pushed up via weewx), here's the URL:

[http://ae3.homelinux.net:81/weather/](url)

I'm four versions behind in the MeteoTemplate updates, so there may be even more blocks and plugins available by now.....

**Comment by trancen** [comment]
I was certain I could / have done upd before through the firewall...  Thanks for the heads up on MeteoTemplate. Looks pretty awesome, had not seen that one before.  I will have a look at just run weewx on my pi as well... Currently trying to setup https://home-assistant.io on it so I will see what load it takes up before loading weewx
