### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by GarryALockyer** [captain-coredump/weatherflow-udp#11]
I have the latest driver working on Weewx 4.1.1 and Belchertown 1.1.

Thank you very much for the driver!

I'm running weewx on a Raspberry Pi so want to absolutely minmize SD card writes.  Is there a way to control logging from the driver, ideally using the new logging facility in weewx 4?  I want to not log informational messages such as:

"Listening for UDP broadcasts. . ."

Regards,

Garry

**Comment by GarryALockyer** [comment]
I have modified weatherflowudp.py to use WeeWX V4 logging.  I've never updated a fork before and don't want to mess anything up, so am posting the updated code here:

[weatherflowudpGAL.zip](https://github.com/captain-coredump/weatherflow-udp/files/4762450/weatherflowudpGAL.zip)

I did NOT edit the python2 version.

Your feedback is welcomed!

Regards,

Garry

**Comment by fcaron71** [comment]
Any luck with this? I am trying to resolve the same issue. Thanks.

**Comment by GarryALockyer** [comment]
I’ll look at this later today.

Regards,

Garry Lockyer
C: +1.250.689.0686
H: +1.250.495.5343
E: Garry@Lockyer.ca

**Comment by captain-coredump** [comment]
Garry, et al,

1) syslog to /dev/null unless you are actively troubleshooting an issue.

2) ...or store logs on a RAM disk.

3) While you're at it, store the HTML/reports on another RAM disk, to save those SD card write cycles every 5 minutes.

RAM disk definitions from my own WeeWX Pi's /etc/fstab, for two WeeWX instances and a cache folder for MeteoTemplate.  Modify to suit your local installations:

weewx_reports /var/weewx/reports tmpfs size=20M,noexec,nosuid,nodev 0 0
weewx_reports2 /var/weewx/reports2 tmpfs size=20M,noexec,nosuid,nodev 0 0
mt_cache /var/www/html/weather/cache tmpfs size=20M,noexec,nosuid,nodev 0 0

I'm pretty sure that there are articles on the Raspberry Pi and saving SD card write cycles on the WeeWX Github/wiki with details and other advice.....

-- 
Sent from my iEtch-a-Sketch via subspace
