### ISSUE TITLE
Explain packet visiblity in README.md

### ISSUE THREAD

**Issue by bernd-wechner** [captain-coredump/weatherflow-udp#5]
I have a Weatherflow SKY, AIR and hub in service now. This project is exciting as I'd like basically to own my own weather data and log it in a local database (happy for it to go out to smartweather's databases as well, I don't mind sharing but I do want to keep it locally as well).

Reading the README though I am left with an uncertainty that I think it would be nice to address there. Namely how does weatherflow-udp see the Hub's transmissions.

I am rather ignorant in this space. I suspect the Weatherflow hub sends UDP packets back to the weatherflow.com and that we can sniff those on the way past. But the only place they'd be reliably visible is on my gateway router surely. The README currently suggests they are broadcast on the LAN. That seems a lot of unnecessary traffic depending entirely on the frequency of the data I guess, and is worth clarifying. Of course if they are broadcast then any device on my LAN could see them.

Clarifying all this would be pleasing.

**Comment by Vertikar** [comment]
You're correct in that this picks up the UDP packets that are broadcast on the LAN.
If you want to see the raw data from the broadcasts, you can use this tool: https://github.com/vinceskahan/weatherflow-udp-listener
